import React from 'react';
import Dashboard from './Dashboard';
import './assets/globals.css';

export const metadata = {
  title: 'Sales Flow',
  description: 'Generated by Felipe França',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      
      <body>
        {children}
        <Dashboard />
      </body>
    </html>
  )
}
