import React from 'react';
import Dashboard from './Dashboard';
import './assets/globals.css';
import { CartProvider } from './pages/cart/CartContext';

export const metadata = {
  title: 'Sales Flow',
  description: 'Generated by Felipe França',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <CartProvider>
          {children}
          <Dashboard />
        </CartProvider>
      </body>
    </html>
  );
}